import HomeBg from '@/components/Home/HomeBg';
import HomeTitle from '@/components/Home/HomeTitle';
import MainContainer from '@/components/MainContainer';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useEffect, useState } from 'react';
const Home = ()=>{
  

  return (
    <>
      <Head>
        <title>Home::Coocking Time</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>

      <MainContainer>
        <HomeBg />
        <HomeTitle />
      </MainContainer>


     
      
    </>
  )
}

export default Home;


